app:
  image: node:8.9.3
  working_dir: /home/app
  volumes:
    - ./dashboard:/home/app
  ports:
   - 80:80
  links:
    - "api:api"
  command: bash -c "npm install && npm rebuild node-sass && npm run build && npm run fire"
api:
  image: node:latest
  working_dir: /home/app
  volumes:
    - ./api:/home/app
  ports:
   - 3000:3000
  links:
    - "db:database"
  command: bash -c "npm install && npm run start"
db:
  image: mysql
  volumes:
    - ./database:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - 3306:3306